### ISSUE TITLE
VS needs restart after configuring colors

### ISSUE THREAD

**Issue by Epsilekt** [Epsilekt/T4Editor#2]
Tried to reload projectItems and refresh or open/save the document, manually invoking the editor classifier again to reset classifications on the textview, but nothing works. 

When changing the font in the VS Options window, it does refresh everything, so it is possible. 

Any help on this would be very welcome!

**Comment by jpozo20** [comment]
I once had that problem with a colorizer extension I was building, the way I did it was by listening to the creation event of the textviews that hold the classification and update them when the settings changed.

You can look at this code to see if you get the gist of it:
https://github.com/jpozo20/SharpLizer/blob/master/SharpLizer/Classification/TextViewColorizer.cs

You can contact me if you need any further help.

**Comment by Epsilekt** [comment]
Thanks, very helpful! 

Will look into this later this week.

**Comment by Epsilekt** [comment]
Cheers Jefry, I finally fixed this issue now.

Thanks!
