### ISSUE TITLE
T4Editor throws exception when attempting to confirm color changes

### ISSUE THREAD

**Issue by chiefengineer** [Epsilekt/T4Editor#5]
Just installed the gadget, haven't even opened it yet. Wanted to see what the default colors where so selected "Adjust colors". Selected all the tabs, then selected close (the "X" in the upper right corner).
Received an error "Object reference not set to an instance of an object."

Same behavior if I select "Confirm".

In short, a null reference pointer exception occurs if no modifications are made and a simple exit selected.

OOps!

**Comment by Epsilekt** [comment]
Latest update resolved this issue.
